version: "3.8"

networks:
  hadoop_eval:
    driver: bridge

services:
  hadoop-master:
    
    image: hadoop-eval
    container_name: hadoop-master
    hostname: hadoop-master
    ports:
      - "9870:9870"   # HDFS NameNode UI
      - "8088:8088"   # YARN ResourceManager UI
      - "7077:7077"   # Spark Master
      - "9000:9000"   # HDFS port
    networks:
      - hadoop_eval
    depends_on:
      - hadoop-worker1
      - hadoop-worker2

  hadoop-worker1:
 ]
    image: hadoop-eval
    container_name: hadoop-worker1
    hostname: hadoop-worker1
    ports:
      - "8040:8042"
    networks:
      - hadoop_eval

  hadoop-worker2:
   ]
    image: hadoop-eval
    container_name: hadoop-worker2
    hostname: hadoop-worker2
    ports:
      - "8041:8042"
    networks:
      - hadoop_eval



